version: '2'
services:
  elasticsearch:
   image: elasticsearch
   expose:
     - 9200
  redis:
   image : redis:2.8.21
   expose:
     - 6379
  redsmin-proxy:
    image: redsmin/proxy
    environment:
      - REDIS_URI=redis://redis:6379
      - REDSMIN_KEY=please-use-your-key-from-redsmin-app
    links:
      - redis     
  play:
    image: alexproca/play:2.2.3
    volumes:
      - .:/app:rw
    ports:
      - "9000:9000"
    links:
      - elasticsearch
      - redis
    working_dir: /app
    stdin_open: true
    restart: always
    env_file:
      - run.env
    command: play run
