version: '2'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.dockerfile
    expose:
     - 9200
  redis:
   image : redis:3.2.11
   expose:
     - 6379
  play:
    build:
      context: .
      dockerfile: play.dockerfile
    volumes:
      - .:/app:rw
    ports:
      - "9000:9000"
    links:
      - elasticsearch
      - redis
    working_dir: /app
    stdin_open: true
    restart: always
    env_file:
      - run.env
    command: play run